export { IGym } from "./models/gym"
export { IAddress } from "./models/address"
export { ISchedule } from "./models/schedule"
export { IPrice } from "./models/price"
export { IAdditionalInformation } from "./models/additional-information"
export { IEmployee } from "./models/employee"